# Generated by Django 4.2.7 on 2023-12-03 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kondate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast', models.TextField(blank=True, verbose_name='朝食')),
                ('lunch', models.TextField(blank=True, verbose_name='昼食')),
                ('dinner', models.TextField(blank=True, verbose_name='夕食')),
                ('snacking', models.TextField(blank=True, verbose_name='間食')),
                ('created', models.DateTimeField(verbose_name='作成日')),
            ],
        ),
    ]
