# Generated by Django 4.2.7 on 2023-12-03 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kondate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kondate',
            name='category',
            field=models.CharField(choices=[('weekday', '平日'), ('holiday', '休日'), ('other', 'その他')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
