# Generated by Django 4.2.7 on 2023-12-04 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kondate', '0003_kondate_eatday_alter_kondate_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kondate',
            name='eatday',
        ),
    ]
