# Generated by Django 4.2.7 on 2023-12-04 01:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kondate', '0004_remove_kondate_eatday'),
    ]

    operations = [
        migrations.AddField(
            model_name='kondate',
            name='eatday',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='食事日'),
        ),
    ]
