# Generated by Django 4.2.7 on 2023-12-05 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kondate', '0005_kondate_eatday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kondate',
            options={'ordering': ['eatday']},
        ),
        migrations.AddField(
            model_name='kondate',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kondate',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='記録日時'),
        ),
    ]
